/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supervising;

import classes.DBConnecter;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mahmoud
 */
public class jloggin extends javax.swing.JFrame {

    boolean testConection;
    // Supervisor sp = new Supervisor() ;
    

    /**
     * Creates new form jloggin
     */
    public jloggin() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        loginBG = new javax.swing.JPanel();
        jButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logpassword = new javax.swing.JPasswordField();
        logusername = new javax.swing.JTextField();
        repence = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        loginBG.setBackground(new java.awt.Color(255, 255, 255));

        jButton.setBackground(new java.awt.Color(153, 153, 153));
        jButton.setText("login");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("user name");

        jLabel2.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("password");

        repence.setFont(new java.awt.Font("Freestyle Script", 1, 24)); // NOI18N
        repence.setForeground(new java.awt.Color(204, 0, 51));

        jLabel3.setBackground(new java.awt.Color(51, 0, 51));
        jLabel3.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel3.setText("login");

        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout loginBGLayout = new javax.swing.GroupLayout(loginBG);
        loginBG.setLayout(loginBGLayout);
        loginBGLayout.setHorizontalGroup(
            loginBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBGLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(loginBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(loginBGLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginBGLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logusername, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBGLayout.createSequentialGroup()
                .addContainerGap(562, Short.MAX_VALUE)
                .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(loginBGLayout.createSequentialGroup()
                .addGroup(loginBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginBGLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginBGLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginBGLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(repence, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginBGLayout.setVerticalGroup(
            loginBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBGLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(repence, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(loginBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logusername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(loginBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(logpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void loginkey(){
        PreparedStatement st=null;
       ResultSet rs=null;
        Connection   conn=null;
        boolean b=false;
        
        this.close();
        
            Supervisor sp = new Supervisor() ;
           sp.setVisible(true);
         
//        try {
//            
//           //Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/supervisor", "jasser", "jasser");
//           //  conn=DBConnecter.connectionDB();
//                      //  String user="jasser",password="jasser",url="jdbc:derby:managedata;create=true;user=jasser;password=jasser";
//
//             conn = DBConnecter.connectionDB();
//             System.out.println("ffffffffffffffffffffffff:: --------->"+ conn);
//             st =conn.prepareStatement("SELECT * FROM LOGGERS");
//             rs = st.executeQuery();
//              System.out.println("ffffffffffffffffffffffff:: <--------->");
//            while (rs.next()){
//                System.out.println("ffffffffffffffffffffffff:: <---------");
//                if(rs.getString(2).equals(logusername.getText()) && rs.getString(3).equals(logpassword.getText())){
//                  b=true;
//                   
//                   
//                    break;
//
//                }
//            }
//           
//                    
//        } catch (SQLException ex) {
//            Logger.getLogger(jloggin.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(jloggin.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            Logger.getLogger(jloggin.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            Logger.getLogger(jloggin.class.getName()).log(Level.SEVERE, null, ex);
//        } 
////        catch (ClassNotFoundException ex) {
////            Logger.getLogger(jloggin.class.getName()).log(Level.SEVERE, null, ex);
////        } catch (InstantiationException ex) {
////            Logger.getLogger(jloggin.class.getName()).log(Level.SEVERE, null, ex);
////        } catch (IllegalAccessException ex) {
////            Logger.getLogger(jloggin.class.getName()).log(Level.SEVERE, null, ex);
////        }
//        finally{
//        
//           try {
//               rs.close();
//               st.close();
//           } catch (SQLException ex) {
//               Logger.getLogger(jloggin.class.getName()).log(Level.SEVERE, null, ex);
//           }
//       
//        }
//        
//         if(b){
//                  
//           this.close();
//           Supervisor sp = new Supervisor() ;
//           sp.setVisible(true);
//          
//         }
//            else 
//             JOptionPane.showMessageDialog(null, "nope!!!!! mot de pass 8alta  ");
    }
    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
     //  loginkey();
//        Supervisor sp = new Supervisor() ;
      //  sp.setVisible(true);
//        try {
//            boolean b;
//           // Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/supervisor", "jasser", "jasser");
//           Connection conn=DBConnecter.connectionDB();
//           System.out.println(conn);
//           System.out.println("hedhi connection t3adet ou nn ");
//            Statement st =conn.createStatement();
//            ResultSet rs = st.executeQuery("SELECT * FROM LOGGERS");
//            
//            while (rs.next()){
//
//                if(rs.getString(2).equals(logusername.getText()) && rs.getString(3).equals(logpassword.getText())){
//                    b=true;
//                    repence.setText("sa77it mot de pass s7i7a    " + "hedhi user name  "+rs.getString(2)+"  whedhi password  "+rs.getString(3)+"    "+ logpassword.getText());
//                     System.out.println("hedhi user name  "+rs.getString(2)+"  whedhi password  "+rs.getString(3));
//                 Supervisor  sp =new Supervisor();
//                 sp.setVisible(true);
//                 //  int j= jloggin.HIDE_ON_CLOSE;
//                    
//                    break;
//
//                }
//                else {
//                    b=false;
//                    repence.setText("nope!!!!! mot de pass 8alta");
//                }
//            }
//
//        } catch (SQLException ex) {
//            Logger.getLogger(jloggin.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(jloggin.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            Logger.getLogger(jloggin.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            Logger.getLogger(jloggin.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton1KeyPressed
          
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
  loginkey();

    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void close (){
    
    
    WindowEvent winclosingevent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclosingevent);
    
    
    
    }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jloggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jloggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jloggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jloggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jloggin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel loginBG;
    private javax.swing.JPasswordField logpassword;
    private javax.swing.JTextField logusername;
    private javax.swing.JLabel repence;
    // End of variables declaration//GEN-END:variables
 
}
